version: '3.5'

services:
  mysql:
    image: mysql:8.0
    container_name: zabbix-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zabbix_network  

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    container_name: zabbix-server
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "10051:10051"
    volumes:
      - ./zabbix_server_data:/var/lib/zabbix
    restart: unless-stopped
    networks:
      - zabbix_network

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:alpine-6.4-latest
    container_name: zabbix-web
    depends_on:
      zabbix-server:
        condition: service_started
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    volumes:
      - ./apache_status.conf:/etc/apache2/conf.d/status.conf      
    restart: unless-stopped
    networks:
      - zabbix_network

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4-latest
    container_name: zabbix-agent
    depends_on:
      zabbix-server:
        condition: service_started
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: zabbix-agent
      ZBX_LISTENIP: 0.0.0.0
    restart: unless-stopped
    networks:
      - zabbix_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3333:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - zabbix_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - zabbix_network

  apache-exporter:
    image: bitnami/apache-exporter:latest
    container_name: apache-exporter
    environment:
      SCRAPE_URI: http://zabbix-web:8080/server-status?auto
    ports:
      - "9117:9117"
    depends_on:
      - zabbix-web
    restart: unless-stopped
    networks:
      - zabbix_network

networks:
  zabbix_network:
    driver: bridge